name: "Oven test"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Bun
        run: npm install -g bun
      - name: Install dependencies
        run: bun install --no-save
      - name: Run tests
        run: bun test
